stages:
  - build
  - test

#################################### build ####################################

windows msvc x64 build:
  stage: build
  tags:
    - msvc
    - windows
    - x64
  artifacts:
    paths:
      - build/
  before_script:
    - call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Auxiliary\\Build\\vcvars64.bat"
  script:
    - mkdir -Force build
    - cd build
    - cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release "-DCMAKE_TOOLCHAIN_FILE=C:/Users/shen/Documents/git/vcpkg/scripts/buildsystems/vcpkg.cmake"
    - ninja

windows msys2 ucrt x64 build:
  stage: build
  tags:
    - gcc
    - msys2
    - windows
    - x64
  artifacts:
    paths:
      - build/
  script:
    - mkdir -Force build
    - cd build
    - C:\tools\msys64\usr\bin\bash -lc 'cmake .. -G Ninja'
    - C:\tools\msys64\usr\bin\bash -lc 'ninja'

windows msys2 clang x64 build:
  stage: build
  tags:
    - clang
    - msys2
    - windows
    - x64
  artifacts:
    paths:
      - build/
  script:
    - mkdir -Force build
    - cd build
    - C:\tools\msys64\usr\bin\bash -lc 'cmake .. -G Ninja'
    - C:\tools\msys64\usr\bin\bash -lc 'ninja'


macos clang x64 build:
  stage: build
  tags:
    - macos
    - x64
  artifacts:
    paths:
      - build/
  script:
    - mkdir -p build
    - cd build
    - cmake .. -G Ninja
    - ninja

linux alpine x64 build:
  stage: build
  image: registry.cn-shanghai.aliyuncs.com/shen3/qnemu-devel:alpine
  tags:
    - linux
    - docker
    - x64
  artifacts:
    paths:
        - build/
  script:
    - mkdir -p build
    - cd build
    - cmake .. -G Ninja
    - ninja

linux alpine arm64 build:
  stage: build
  image: registry.cn-shanghai.aliyuncs.com/shen3/qnemu-devel:alpine
  tags:
    - linux
    - docker
    - arm64
  artifacts:
    paths:
        - build/
  script:
    - mkdir -p build
    - cd build
    - cmake .. -G Ninja
    - ninja

linux arch x64 build:
  stage: build
  image: registry.cn-shanghai.aliyuncs.com/shen3/qnemu-devel:arch
  tags:
    - linux
    - docker
    - x64
  artifacts:
    paths:
        - build/
  script:
    - mkdir -p build
    - cd build
    - cmake .. -G Ninja
    - ninja

linux centos x64 build:
  stage: build
  image: registry.cn-shanghai.aliyuncs.com/shen3/qnemu-devel:centos
  tags:
    - linux
    - docker
    - x64
  artifacts:
    paths:
        - build/
  script:
    - mkdir -p build
    - cd build
    - cmake .. -G Ninja
    - ninja

linux centos arm64 build:
  stage: build
  image: registry.cn-shanghai.aliyuncs.com/shen3/qnemu-devel:centos
  tags:
    - linux
    - docker
    - arm64
  artifacts:
    paths:
        - build/
  script:
    - mkdir -p build
    - cd build
    - cmake .. -G Ninja
    - ninja

linux debian x64 build:
  stage: build
  image: registry.cn-shanghai.aliyuncs.com/shen3/qnemu-devel:debian
  tags:
    - linux
    - docker
    - x64
  artifacts:
    paths:
        - build/
  script:
    - mkdir -p build
    - cd build
    - cmake .. -G Ninja
    - ninja

linux debian arm64 build:
  stage: build
  image: registry.cn-shanghai.aliyuncs.com/shen3/qnemu-devel:debian
  tags:
    - linux
    - docker
    - arm64
  artifacts:
    paths:
        - build/
  script:
    - mkdir -p build
    - cd build
    - cmake .. -G Ninja
    - ninja

linux fedora x64 build:
  stage: build
  image: registry.cn-shanghai.aliyuncs.com/shen3/qnemu-devel:fedora
  tags:
    - linux
    - docker
    - x64
  artifacts:
    paths:
        - build/
  script:
    - mkdir -p build
    - cd build
    - cmake .. -G Ninja
    - ninja

linux fedora arm64 build:
  stage: build
  image: registry.cn-shanghai.aliyuncs.com/shen3/qnemu-devel:fedora
  tags:
    - linux
    - docker
    - arm64
  artifacts:
    paths:
        - build/
  script:
    - mkdir -p build
    - cd build
    - cmake .. -G Ninja
    - ninja

linux ubuntu x64 build:
  stage: build
  image: registry.cn-shanghai.aliyuncs.com/shen3/qnemu-devel:ubuntu
  tags:
    - linux
    - docker
    - x64
  artifacts:
    paths:
        - build/
  script:
    - mkdir -p build
    - cd build
    - cmake .. -G Ninja
    - ninja

linux ubuntu arm64 build:
  stage: build
  image: registry.cn-shanghai.aliyuncs.com/shen3/qnemu-devel:ubuntu
  tags:
    - linux
    - docker
    - arm64
  artifacts:
    paths:
        - build/
  script:
    - mkdir -p build
    - cd build
    - cmake .. -G Ninja
    - ninja

linux void x64 build:
  stage: build
  image: registry.cn-shanghai.aliyuncs.com/shen3/qnemu-devel:void
  tags:
    - linux
    - docker
    - x64
  artifacts:
    paths:
        - build/
  script:
    - mkdir -p build
    - cd build
    - cmake .. -G Ninja
    - ninja

#################################### test ####################################

windows msvc x64 test:
  stage: test
  tags:
    - msvc
    - windows
    - x64
  needs:
    - job: windows msvc x64 build
  before_script:
    - call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Auxiliary\\Build\\vcvars64.bat"
  script:
    - cd build
    - ninja test

windows msys2 ucrt x64 test:
  stage: test
  tags:
    - gcc
    - msys2
    - windows
    - x64
  needs:
    - job: windows msys2 ucrt x64 build
  script:
    - cd build
    - C:\tools\msys64\usr\bin\bash -lc 'ninja test'

windows msys2 clang x64 test:
  stage: test
  tags:
    - clang
    - msys2
    - windows
    - x64
  needs:
    - job: windows msys2 clang x64 build
  script:
    - cd build
    - C:\tools\msys64\usr\bin\bash -lc 'ninja test'

macos clang x64 test:
  stage: test
  tags:
    - macos
    - x64
  needs:
    - job: macos clang x64 build
  script:
    - cd build
    - ninja test

linux alpine x64 test:
    stage: test
    image: registry.cn-shanghai.aliyuncs.com/shen3/qnemu-devel:alpine
    tags:
        - linux
        - docker
        - x64
    needs:
      - job: linux alpine x64 build
    script:
        - cd build
        - ninja test

linux alpine arm64 test:
    stage: test
    image: registry.cn-shanghai.aliyuncs.com/shen3/qnemu-devel:alpine
    tags:
        - linux
        - docker
        - arm64
    needs:
      - job: linux alpine arm64 build
    script:
        - cd build
        - ninja test

linux arch x64 test:
    stage: test
    image: registry.cn-shanghai.aliyuncs.com/shen3/qnemu-devel:arch
    tags:
        - linux
        - docker
        - x64
    needs:
      - job: linux arch x64 build
    script:
        - cd build
        - ninja test

linux centos x64 test:
    stage: test
    image: registry.cn-shanghai.aliyuncs.com/shen3/qnemu-devel:centos
    tags:
        - linux
        - docker
        - x64
    needs:
      - job: linux centos x64 build
    script:
        - cd build
        - ninja test

linux centos arm64 test:
    stage: test
    image: registry.cn-shanghai.aliyuncs.com/shen3/qnemu-devel:centos
    tags:
        - linux
        - docker
        - arm64
    needs:
      - job: linux centos arm64 build
    script:
        - cd build
        - ninja test

linux debian x64 test:
    stage: test
    image: registry.cn-shanghai.aliyuncs.com/shen3/qnemu-devel:debian
    tags:
        - linux
        - docker
        - x64
    needs:
      - job: linux debian x64 build
    script:
        - cd build
        - ninja test

linux debian arm64 test:
    stage: test
    image: registry.cn-shanghai.aliyuncs.com/shen3/qnemu-devel:debian
    tags:
        - linux
        - docker
        - arm64
    needs:
      - job: linux debian arm64 build
    script:
        - cd build
        - ninja test

linux fedora x64 test:
    stage: test
    image: registry.cn-shanghai.aliyuncs.com/shen3/qnemu-devel:fedora
    tags:
        - linux
        - docker
        - x64
    needs:
      - job: linux fedora x64 build
    script:
        - cd build
        - ninja test

linux fedora arm64 test:
    stage: test
    image: registry.cn-shanghai.aliyuncs.com/shen3/qnemu-devel:fedora
    tags:
        - linux
        - docker
        - arm64
    needs:
      - job: linux fedora arm64 build
    script:
        - cd build
        - ninja test

linux ubuntu x64 test:
    stage: test
    image: registry.cn-shanghai.aliyuncs.com/shen3/qnemu-devel:ubuntu
    tags:
        - linux
        - docker
        - x64
    needs:
      - job: linux ubuntu x64 build
    script:
        - cd build
        - ninja test

linux ubuntu arm64 test:
    stage: test
    image: registry.cn-shanghai.aliyuncs.com/shen3/qnemu-devel:ubuntu
    tags:
        - linux
        - docker
        - arm64
    needs:
      - job: linux ubuntu arm64 build
    script:
        - cd build
        - ninja test

linux void x64 test:
    stage: test
    image: registry.cn-shanghai.aliyuncs.com/shen3/qnemu-devel:void
    tags:
        - linux
        - docker
        - x64
    needs:
      - job: linux void x64 build
    script:
        - cd build
        - ninja test
