stages:
  - build
  - test

#################################### build ####################################

# windows msvc x64 build:
#   stage: build
#   tags:
#     - msvc
#     - windows
#     - x64
#   artifacts:
#     paths:
#       - build/
#   before_script:
#     - call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Auxiliary\\Build\\vcvars64.bat"
#   script:
#     - mkdir -Force build
#     - cd build
#     - cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release
#     - ninja

macos clang x64 build:
  stage: build
  tags:
    - macos
    - x64
  artifacts:
    paths:
      - build/
  script:
    - mkdir -p build
    - cd build
    - cmake .. -G Ninja
    - ninja

linux alpine x64 build:
  stage: build
  image: registry.cn-hangzhou.aliyuncs.com/shen3/qnemu-devel:alpine
  tags:
    - linux
    - docker
    - x64
  artifacts:
    paths:
        - build/
  script:
    - mkdir -p build
    - cd build
    - cmake .. -G Ninja
    - ninja

linux alpine arm64 build:
  stage: build
  image: registry.cn-hangzhou.aliyuncs.com/shen3/qnemu-devel:alpine
  tags:
    - linux
    - docker
    - arm64
  artifacts:
    paths:
        - build/
  script:
    - mkdir -p build
    - cd build
    - cmake .. -G Ninja
    - ninja

#################################### test ####################################

# windows msvc x64 test:
#   stage: test
#   tags:
#     - msvc
#     - windows
#     - x64
#   needs:
#     - job: windows msvc x64 build
#   before_script:
#     - call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Auxiliary\\Build\\vcvars64.bat"
#   script:
#     - cd build
#     - ninja test

macos clang x64 test:
  stage: test
  tags:
    - macos
    - x64
  needs:
    - job: macos clang x64 build
  script:
    - cd build
    - ninja test

linux alpine x64 test:
    stage: test
    image: registry.cn-hangzhou.aliyuncs.com/shen3/qnemu-devel:alpine
    tags:
        - linux
        - docker
        - x64
    needs:
      - job: linux alpine x64 build
    script:
        - cd build
        - ninja test

linux alpine arm64 test:
    stage: test
    image: registry.cn-hangzhou.aliyuncs.com/shen3/qnemu-devel:alpine
    tags:
        - linux
        - docker
        - arm64
    needs:
      - job: linux alpine arm64 build
    script:
        - cd build
        - ninja test
